/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lpii02;

import LPII02.Business.Services.AccessGroupBusiness;
import LPII02.Business.Services.UserBusiness;
import LPII02.Domain.Entities.AccessGroup;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eleni Oliveira
 */
public class JFProfile extends javax.swing.JInternalFrame {

    private UserBusiness _userBusiness = new UserBusiness();
    private boolean _isLoad = false;

    /**
     * Creates new form JFProfile
     */
    public JFProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPerCod = new javax.swing.JLabel();
        lblPerNome = new javax.swing.JLabel();
        lblPerLogin = new javax.swing.JLabel();
        lblPerSenha = new javax.swing.JLabel();
        lblPerGAcesso = new javax.swing.JLabel();
        txtPerCod = new javax.swing.JTextField();
        txtPerNome = new javax.swing.JTextField();
        txtPerLogin = new javax.swing.JTextField();
        txtPerSenha = new javax.swing.JTextField();
        txtPerGAcesso = new javax.swing.JComboBox<AccessGroup>();
        lblPerAvatar = new javax.swing.JLabel();
        lblPerAvatarImg = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Perfil de Usuário");
        setPreferredSize(new java.awt.Dimension(1228, 502));
        addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                formHierarchyChanged(evt);
            }
        });

        lblPerCod.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPerCod.setText("Código:");

        lblPerNome.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPerNome.setText("Nome:");

        lblPerLogin.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPerLogin.setText("Login:");

        lblPerSenha.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPerSenha.setText("Senha:");

        lblPerGAcesso.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPerGAcesso.setText("Grupo de Acesso:");

        txtPerGAcesso.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        lblPerAvatar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblPerAvatar.setText("Avatar:");

        btnAdd.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAdd.setText("Adicionar");

        btnConsultar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setPreferredSize(new java.awt.Dimension(99, 27));

        btnAlterar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setPreferredSize(new java.awt.Dimension(99, 27));

        btnRemover.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.setPreferredSize(new java.awt.Dimension(99, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPerCod)
                            .addComponent(lblPerNome)
                            .addComponent(lblPerLogin)
                            .addComponent(lblPerSenha)
                            .addComponent(lblPerGAcesso))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPerSenha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerLogin, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerCod, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPerGAcesso, 0, 291, Short.MAX_VALUE))
                        .addGap(138, 138, 138)
                        .addComponent(lblPerAvatar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPerAvatarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(33, 33, 33)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(282, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPerAvatarImg, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPerCod)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPerCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPerAvatar)))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPerNome)
                            .addComponent(txtPerNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPerLogin)
                            .addComponent(txtPerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPerSenha)
                            .addComponent(txtPerSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPerGAcesso)
                            .addComponent(txtPerGAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        setBounds(0, 0, 1228, 502);
    }// </editor-fold>//GEN-END:initComponents

    private void loadGroups() throws InstantiationException, IllegalAccessException {
        AccessGroupBusiness acBusiness = new AccessGroupBusiness();
        List<AccessGroup> groups = new ArrayList<AccessGroup>();
        AccessGroup ag = acBusiness.getInstance();

        ag.setId(0);
        ag.setName("Selecione");

        groups.add(ag);
        groups.addAll(acBusiness.get());

        DefaultComboBoxModel<AccessGroup> model = new DefaultComboBoxModel<AccessGroup>(groups.toArray(new AccessGroup[]{}));
        this.txtPerGAcesso.setModel(model);
        model.setSelectedItem(groups.get(0));
    }

    private void formHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formHierarchyChanged
        try {
            this.loadGroups();
            this._isLoad = true;
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "Ocorreu um erro durante o carregamento do formulário, tente novamente.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formHierarchyChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel lblPerAvatar;
    private javax.swing.JLabel lblPerAvatarImg;
    private javax.swing.JLabel lblPerCod;
    private javax.swing.JLabel lblPerGAcesso;
    private javax.swing.JLabel lblPerLogin;
    private javax.swing.JLabel lblPerNome;
    private javax.swing.JLabel lblPerSenha;
    private javax.swing.JTextField txtPerCod;
    private javax.swing.JComboBox<AccessGroup> txtPerGAcesso;
    private javax.swing.JTextField txtPerLogin;
    private javax.swing.JTextField txtPerNome;
    private javax.swing.JTextField txtPerSenha;
    // End of variables declaration//GEN-END:variables
}
