/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lpii02;

import Components.MediaBar;
import LPII02.Domain.Entities.Course;
import LPII02.Domain.Entities.Lesson;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.control.Slider;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.Priority;
import javafx.scene.layout.Region;
import javafx.scene.paint.Color;
import javafx.scene.text.Text;
import javax.swing.JOptionPane;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javax.swing.SwingUtilities;

/**
 *
 * @author Gustavo
 */
public class JPDoCourse extends javax.swing.JPanel {

    private final List<Lesson> _lessons;
    private JFXPanel _fxPanel;
    private int _ixLesson = 0;

    /**
     * Creates new form JPDoCourse
     */
    public JPDoCourse(List<Lesson> lessons) {
        initComponents();

        this._lessons = lessons;
        this._fxPanel = new JFXPanel();
        this.jpStream.add(this._fxPanel);

        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                initFX();
            }
        });
    }

    private void initFX() {
        // This method is invoked on the JavaFX thread
        Scene scene = createScene();
        this._fxPanel.setScene(scene);
        this._fxPanel.setSize(728, 400);
        this._fxPanel.setLocation(0, 0);
        this._fxPanel.setVisible(true);
    }

    private Scene createScene() {
        //Instantiating Media class
        File fileTemp = null;
        Scene scene = null;

        try {
            fileTemp = new File("C:\\Users\\Gustavo\\Desktop\\EC5\\JavaParam\\tempVideo.mp4");

            if (fileTemp.exists()) {
                fileTemp.delete();
            }

            fileTemp.createNewFile();

            FileOutputStream fStream = new FileOutputStream(fileTemp);
            fStream.write(this._lessons.get(this._ixLesson).getContent());
            fStream.close();

            Media media = new Media(fileTemp.toURI().toString());
            MediaPlayer mediaPlayer = new MediaPlayer(media);
            MediaView mediaView = new MediaView(mediaPlayer);
            MediaBar mBar = new MediaBar(mediaPlayer);
            BorderPane borderPane = new BorderPane();
            
            borderPane.setBottom(mediaView);
            borderPane.setTop(mBar);

            //by setting this property to true, the Video will be played   
            mediaPlayer.setAutoPlay(true);

            //setting group and scene   
            Group root = new Group();
            root.getChildren().add(borderPane);
            scene = new Scene(root, 728, 450, Color.ALICEBLUE);

            SwingUtilities.invokeLater(new Runnable() {
                @Override
                public void run() {
                    //Code to change Swing data.
                    lblClass.setText(
                            "Título: "
                            + _lessons.get(_ixLesson).getName() + ";"
                            + " Ordem: "
                            + (_ixLesson + 1)
                            + " / "
                            + _lessons.size());
                }
            });
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    null,
                    "Ocorreu um erro ao carregar a aula, tente novamente.",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }

        return scene;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpStream = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblClass = new javax.swing.JLabel();

        addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                formHierarchyChanged(evt);
            }
        });

        javax.swing.GroupLayout jpStreamLayout = new javax.swing.GroupLayout(jpStream);
        jpStream.setLayout(jpStreamLayout);
        jpStreamLayout.setHorizontalGroup(
            jpStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 728, Short.MAX_VALUE)
        );
        jpStreamLayout.setVerticalGroup(
            jpStreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        btnNext.setText(">");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setText("<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblClass.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblClass.setText("Nome Aula e Ordem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpStream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNext)
                        .addGap(18, 18, 18)
                        .addComponent(lblClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpStream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnBack)
                    .addComponent(lblClass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formHierarchyChanged
        try {
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ocorreu um erro ao exibir a primeira aula",
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);

            this.setVisible(false);

            try {
                this.finalize();
            } catch (Throwable ex1) {
                Logger.getLogger(JPDoCourse.class.getName()).log(Level.SEVERE, null, ex1);
            }
        }
    }//GEN-LAST:event_formHierarchyChanged

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        if (this._ixLesson + 1 == this._lessons.size()) {
            return;
        }

        this._ixLesson++;

        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                try {
                    initFX();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Ocorreu um erro ao carregar a aula, tente novamente",
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (this._ixLesson == 0) {
            return;
        }

        this._ixLesson--;

        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                try {
                    initFX();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Ocorreu um erro ao carregar a aula, tente novamente",
                            "Erro",
                            JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JPanel jpStream;
    private javax.swing.JLabel lblClass;
    // End of variables declaration//GEN-END:variables
}
